language: php
addons:
  sonarcloud:
    organization: "ldap-account-manager"
php:
  - '7.3'

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - phpunit
  - ls -l code-coverage/*
  - sonar-scanner
  - pip install codespell
  - cd lam
  - ./codespell.sh
