language: php
addons:
  sonarcloud:
    organization: "ldap-account-manager"
php:
  - '7.2'

cache:
  directories:
    - '$HOME/.sonar/cache'

script:
  - phpunit
  - ls -l code-coverage/*
  - sonar-scanner
